// V20 system UI labels (RU/EN).
import type { Lang } from '@/systems/types';

export const LABELS: Partial<Record<Lang, Record<string, string>>> = {
  ru: {
    profile: 'Профиль', attributes: 'Атрибуты', abilities: 'Способности',
    advantages: 'Преимущества', virtues: 'Добродетели', state: 'Состояние',
    history: 'История', checklist: 'Создание персонажа',
    physical: 'Физические', social: 'Социальные', mental: 'Ментальные',
    talents: 'Таланты', skills: 'Навыки', knowledges: 'Знания',
    disciplines: 'Дисциплины', backgrounds: 'Преимущества',
    merits: 'Достоинства', flaws: 'Недостатки',
    name: 'Имя', player: 'Игрок', chronicle: 'Хроника',
    nature: 'Натура', demeanor: 'Маска', concept: 'Концепт',
    clan: 'Клан', generation: 'Поколение', sire: 'Сир',
    humanity: 'Человечность', path: 'Путь', willpower: 'Воля',
    bloodPool: 'Запас крови', health: 'Здоровье', experience: 'Опыт',
    weakness: 'Слабость',
    conscience: 'Совесть', conviction: 'Убеждённость',
    selfControl: 'Самоконтроль', instinct: 'Инстинкт', courage: 'Смелость',
    bruised: 'Ушиблен', hurt: 'Болен', injured: 'Ранен',
    wounded: 'Контужен', mauled: 'Изувечен', crippled: 'Покалечен',
    incapacitated: 'Недееспособен',
    bashing: 'Ушибающий', lethal: 'Летальный', aggravated: 'Отягощённый',
    roll: 'Бросок', pool: 'Пул', difficulty: 'Сложность',
    successes: 'Успехи', failure: 'Провал', botch: 'Боч',
    rollIt: 'Бросить', history20: 'История бросков', specialty: 'Специализация',
    addItem: 'Добавить', remove: 'Убрать', notes: 'Заметки', avatar: 'Аватар',
    share: 'Поделиться', signIn: 'Войти через Google',
    saved: 'Сохранено', saving: 'Сохраняю…', offline: 'Локально',
    validationOk: 'Лист валиден', validationFail: 'Ошибки',
  },
  en: {
    profile: 'Profile', attributes: 'Attributes', abilities: 'Abilities',
    advantages: 'Advantages', virtues: 'Virtues', state: 'State', history: 'History',
    checklist: 'Character creation',
    physical: 'Physical', social: 'Social', mental: 'Mental',
    talents: 'Talents', skills: 'Skills', knowledges: 'Knowledges',
    disciplines: 'Disciplines', backgrounds: 'Backgrounds',
    merits: 'Merits', flaws: 'Flaws',
    name: 'Name', player: 'Player', chronicle: 'Chronicle',
    nature: 'Nature', demeanor: 'Demeanor', concept: 'Concept',
    clan: 'Clan', generation: 'Generation', sire: 'Sire',
    humanity: 'Humanity', path: 'Path', willpower: 'Willpower',
    bloodPool: 'Blood Pool', health: 'Health', experience: 'Experience',
    weakness: 'Weakness',
    conscience: 'Conscience', conviction: 'Conviction',
    selfControl: 'Self-Control', instinct: 'Instinct', courage: 'Courage',
    bruised: 'Bruised', hurt: 'Hurt', injured: 'Injured',
    wounded: 'Wounded', mauled: 'Mauled', crippled: 'Crippled', incapacitated: 'Incapacitated',
    bashing: 'Bashing', lethal: 'Lethal', aggravated: 'Aggravated',
    roll: 'Roll', pool: 'Pool', difficulty: 'Difficulty',
    successes: 'Successes', failure: 'Failure', botch: 'Botch',
    rollIt: 'Roll', history20: 'Roll history', specialty: 'Specialty',
    addItem: 'Add', remove: 'Remove', notes: 'Notes', avatar: 'Avatar',
    share: 'Share', signIn: 'Sign in with Google',
    saved: 'Saved', saving: 'Saving…', offline: 'Local',
    validationOk: 'Sheet is valid', validationFail: 'Issues',
  },
};
